In [85]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

X, y, iris.target_names, iris.feature_names

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [86]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train, X_test, y_train, y_test

(array([[4.9, 3.1, 1.5, 0.1],
        [5.4, 3.9, 1.7, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.9, 3. , 5.1, 1.8],
        [5.1, 3.3, 1.7, 0.5],
        [6.1, 2.8, 4. , 1.3],
        [4.7, 3.2, 1.3, 0.2],
        [5.8, 2.7, 5.1, 1.9],
        [6.9, 3.2, 5.7, 2.3],
        [6.4, 2.8, 5.6, 2.1],
        [5. , 3.5, 1.3, 0.3],
        [7.2, 3.2, 6. , 1.8],
        [4.4, 3.2, 1.3, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [5.6, 2.9, 3.6, 1.3],
        [5.2, 4.1, 1.5, 0.1],
        [5.7, 3.8, 1.7, 0.3],
        [4.9, 3. , 1.4, 0.2],
        [7.4, 2.8, 6.1, 1.9],
        [6.1, 2.6, 5.6, 1.4],
        [6.3, 3.4, 5.6, 2.4],
        [5.6, 2.5, 3.9, 1.1],
        [5. , 2. , 3.5, 1. ],
        [5.1, 3.8, 1.6, 0.2],
        [7.1, 3. , 5.9, 2.1],
        [6.4, 2.7, 5.3, 1.9],
        [6.7, 3. , 5. , 1.7],
        [5.7, 4.4, 1.5, 0.4],
        [5.8, 2.7, 4.1, 1. ],
        [6.4, 3.2, 4.5, 1.5],
        [6.6, 2.9, 4.6, 1.3],
        [6.7, 3.1, 5.6, 2.4],
        [5.7, 3. , 4.2, 1.2],
        [5.5, 2.5, 4. , 1.3],
        [5.8, 2.6, 4. , 1.2],
        [5.4, 3. , 4.5, 1.5],
        [6.8, 3.2, 5.9, 2.3],
        [5.7, 2.9, 4.2, 1.3],
        [4.9, 2.5, 4.5, 1.7],
        [5. , 3. , 1.6, 0.2],
        [6.5, 3. , 5.2, 2. ],
        [5.6, 3. , 4.1, 1.3],
        [5. , 2.3, 3.3, 1. ],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 3. , 4.4, 1.4],
        [5. , 3.4, 1.5, 0.2],
        [5.1, 2.5, 3. , 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [6.7, 2.5, 5.8, 1.8],
        [5. , 3.2, 1.2, 0.2],
        [6.5, 3.2, 5.1, 2. ],
        [6.5, 3. , 5.8, 2.2],
        [4.4, 3. , 1.3, 0.2],
        [6.2, 3.4, 5.4, 2.3],
        [5.5, 4.2, 1.4, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [6.4, 2.8, 5.6, 2.2],
        [5. , 3.6, 1.4, 0.2],
        [5.7, 2.8, 4.5, 1.3],
        [5.9, 3.2, 4.8, 1.8],
        [5.1, 3.4, 1.5, 0.2],
        [6.1, 3. , 4.6, 1.4],
        [6.3, 2.5, 4.9, 1.5],
        [5.5, 2.6, 4.4, 1.2],
        [4.9, 3.1, 1.5, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [7.9, 3.8, 6.4, 2. ],
        [6. , 2.2, 5. , 1.5],
        [6.4, 3.1, 5.5, 1.8],
        [4.8, 3.1, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [6.3, 2.8, 5.1, 1.5],
        [5.3, 3.7, 1.5, 0.2],
        [6. , 2.2, 4. , 1. ],
        [4.6, 3.1, 1.5, 0.2],
        [5.7, 2.6, 3.5, 1. ],
        [5.8, 2.8, 5.1, 2.4],
        [5.1, 3.5, 1.4, 0.3],
        [6.1, 3. , 4.9, 1.8],
        [5.1, 3.8, 1.9, 0.4],
        [6. , 2.7, 5.1, 1.6],
        [5.1, 3.5, 1.4, 0.2],
        [5.4, 3.7, 1.5, 0.2],
        [7.2, 3.6, 6.1, 2.5],
        [5.2, 3.5, 1.5, 0.2],
        [6.5, 2.8, 4.6, 1.5],
        [6.2, 2.9, 4.3, 1.3],
        [6.4, 2.9, 4.3, 1.3],
        [7.7, 2.6, 6.9, 2.3],
        [7.6, 3. , 6.6, 2.1],
        [6.7, 3.3, 5.7, 2.1],
        [6.2, 2.8, 4.8, 1.8],
        [6.9, 3.1, 4.9, 1.5],
        [5.6, 3. , 4.5, 1.5],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [5.8, 4. , 1.2, 0.2],
        [5.1, 3.8, 1.5, 0.3],
        [7.7, 2.8, 6.7, 2. ],
        [6.7, 3. , 5.2, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6. , 2.9, 4.5, 1.5],
        [4.3, 3. , 1.1, 0.1],
        [7.7, 3.8, 6.7, 2.2],
        [6. , 3. , 4.8, 1.8],
        [4.4, 2.9, 1.4, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [6.3, 2.3, 4.4, 1.3],
        [7. , 3.2, 4.7, 1.4],
        [6. , 3.4, 4.5, 1.6],
        [5.4, 3.9, 1.3, 0.4],
        [4.5, 2.3, 1.3, 0.3]]),
 array([[4.6, 3.2, 1.4, 0.2],
        [5.5, 2.4, 3.8, 1.1],
        [6.3, 2.5, 5. , 1.9],
        [5. , 3.4, 1.6, 0.4],
        [5. , 3.3, 1.4, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [5.6, 2.8, 4.9, 2. ],
        [4.9, 3.6, 1.4, 0.1],
        [5.7, 2.8, 4.1, 1.3],
        [4.7, 3.2, 1.6, 0.2],
        [6.3, 2.9, 5.6, 1.8],
        [6.7, 3.1, 4.7, 1.5],
        [6.2, 2.2, 4.5, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [5.6, 2.7, 4.2, 1.3],
        [5.9, 3. , 4.2, 1.5],
        [6.9, 3.1, 5.1, 2.3],
        [5.4, 3.4, 1.5, 0.4],
        [5.7, 2.5, 5. , 2. ],
        [6.8, 3. , 5.5, 2.1],
        [6.3, 2.7, 4.9, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.3, 3.3, 6. , 2.5],
        [6.3, 3.3, 4.7, 1.6],
        [5.8, 2.7, 3.9, 1.2],
        [4.6, 3.6, 1. , 0.2],
        [7.2, 3. , 5.8, 1.6],
        [6.7, 3.1, 4.4, 1.4],
        [5.4, 3.4, 1.7, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [7.3, 2.9, 6.3, 1.8],
        [6.1, 2.8, 4.7, 1.2],
        [7.7, 3. , 6.1, 2.3],
        [6.8, 2.8, 4.8, 1.4],
        [5.8, 2.7, 5.1, 1.9],
        [5.2, 2.7, 3.9, 1.4],
        [4.6, 3.4, 1.4, 0.3]]),
 array([0, 0, 0, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 2, 2, 1,
        1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 1, 1,
        1, 0, 1, 1, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0,
        2, 2, 2, 0, 0, 2, 0, 1, 0, 1, 2, 0, 2, 0, 1, 0, 0, 2, 0, 1, 1, 1,
        2, 2, 2, 2, 1, 1, 2, 2, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 0, 1, 1, 1,
        0, 0]),
 array([0, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 0, 2, 2, 2, 2,
        2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 1, 0]))

In [87]:
X.shape, X_train.shape, X_test.shape, X_train.shape[0] / X.shape[0], X_test.shape[0] / X.shape[0]

((150, 4), (112, 4), (38, 4), 0.7466666666666667, 0.25333333333333335)

In [88]:
y.shape, y_train.shape, y_test.shape, y_train.shape[0] / y.shape[0], y_test.shape[0] / y.shape[0]

((150,), (112,), (38,), 0.7466666666666667, 0.25333333333333335)

In [89]:
y.reshape((150, 1)),y.reshape((-1,))

(array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [90]:
from sklearn.neighbors import KNeighborsClassifier

estimator = KNeighborsClassifier(n_neighbors=3)

estimator.fit(X_train, y_train)

y_predicted = estimator.predict(X_test)

print("Precisión: {:.1f}".format((y_test == y_predicted).mean() * 100))

Precisión: 100.0

In [91]:
X_test, y_test, y_predicted

(array([[4.6, 3.2, 1.4, 0.2],
        [5.5, 2.4, 3.8, 1.1],
        [6.3, 2.5, 5. , 1.9],
        [5. , 3.4, 1.6, 0.4],
        [5. , 3.3, 1.4, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [5.6, 2.8, 4.9, 2. ],
        [4.9, 3.6, 1.4, 0.1],
        [5.7, 2.8, 4.1, 1.3],
        [4.7, 3.2, 1.6, 0.2],
        [6.3, 2.9, 5.6, 1.8],
        [6.7, 3.1, 4.7, 1.5],
        [6.2, 2.2, 4.5, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [5.6, 2.7, 4.2, 1.3],
        [5.9, 3. , 4.2, 1.5],
        [6.9, 3.1, 5.1, 2.3],
        [5.4, 3.4, 1.5, 0.4],
        [5.7, 2.5, 5. , 2. ],
        [6.8, 3. , 5.5, 2.1],
        [6.3, 2.7, 4.9, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.3, 3.3, 6. , 2.5],
        [6.3, 3.3, 4.7, 1.6],
        [5.8, 2.7, 3.9, 1.2],
        [4.6, 3.6, 1. , 0.2],
        [7.2, 3. , 5.8, 1.6],
        [6.7, 3.1, 4.4, 1.4],
        [5.4, 3.4, 1.7, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [7.3, 2.9, 6.3, 1.8],
        [6.1, 2.8, 4.7, 1.2],
        [7.7, 3. , 6.1, 2.3],
        [6.8, 2.8, 4.8, 1.4],
        [5.8, 2.7, 5.1, 1.9],
        [5.2, 2.7, 3.9, 1.4],
        [4.6, 3.4, 1.4, 0.3]]),
 array([0, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 0, 2, 2, 2, 2,
        2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 1, 0]),
 array([0, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 0, 2, 2, 2, 2,
        2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 1, 0]))

In [92]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(estimator, X, y, scoring='accuracy')

print(scores)

[0.96666667 0.96666667 0.93333333 0.96666667 1.        ]

In [93]:
accuracy = scores.mean() * 100

accuracy

96.66666666666669

In [94]:
import numpy as np

x = np.random.uniform(5, 20, (10, 4))

x

array([[13.56692106, 12.81854332, 15.38314793, 14.90489084],
       [10.20658018,  8.96365329, 14.04901228,  6.51911889],
       [ 8.91462437, 19.21417042, 17.05260681, 12.44858791],
       [ 5.62784733, 15.6046075 , 11.90736176, 18.27108173],
       [ 9.87581775, 16.47720905, 18.23656034,  5.94861116],
       [ 6.43805921, 16.62772889, 17.02262823, 16.5805082 ],
       [16.17921171,  6.41752099, 19.48775376,  7.60267337],
       [ 7.95166467,  5.44025846,  5.66156155, 16.51348475],
       [10.44927032,  9.52463066,  7.31838685,  7.44220895],
       [11.49493304, 19.12853929,  7.67299259, 13.98138071]])

In [95]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler().fit_transform(x)

array([[0.75242153, 0.53567098, 0.70312825, 0.726825  ],
       [0.43394699, 0.25580204, 0.6066349 , 0.04629816],
       [0.31150256, 1.        , 0.82387436, 0.52748974],
       [0.        , 0.73794207, 0.45173683, 1.        ],
       [0.40259916, 0.80129382, 0.90950557, 0.        ],
       [0.0767874 , 0.81222172, 0.82170612, 0.86280563],
       [1.        , 0.07095025, 1.        , 0.13423138],
       [0.22023856, 0.        , 0.        , 0.85736651],
       [0.45694782, 0.29652957, 0.11983236, 0.12120928],
       [0.55604996, 0.99378309, 0.14547975, 0.65187979]])

In [96]:
from sklearn.preprocessing import Normalizer

Normalizer().fit_transform(x)

array([[0.47752694, 0.45118562, 0.54145428, 0.52462064],
       [0.49544462, 0.43511085, 0.68196275, 0.31644903],
       [0.29808069, 0.64246939, 0.5701926 , 0.41624678],
       [0.20539122, 0.56949828, 0.43456537, 0.66681264],
       [0.36378331, 0.60695061, 0.67175767, 0.21912165],
       [0.21670542, 0.55969026, 0.5729826 , 0.55810081],
       [0.59454892, 0.23582918, 0.71613025, 0.27938081],
       [0.3987945 , 0.27284163, 0.28394049, 0.82818971],
       [0.59458149, 0.5419679 , 0.41642883, 0.42347452],
       [0.41906889, 0.69736602, 0.27973303, 0.50971691]])

In [97]:
from sklearn.preprocessing import StandardScaler

StandardScaler().fit_transform(x)

array([[ 1.16207539, -0.04172028,  0.42420352,  0.64478559],
       [ 0.04523005, -0.83341482,  0.14178831, -1.23028621],
       [-0.38416533,  1.27177582,  0.7776013 ,  0.09555239],
       [-1.47656093,  0.53046512, -0.31156491,  1.39747117],
       [-0.0647024 ,  0.70967486,  1.02822536, -1.35785264],
       [-1.20727833,  0.74058774,  0.77125532,  1.01945627],
       [ 2.03029821, -1.35632442,  1.29308302, -0.98800173],
       [-0.70421531, -1.55702882, -1.63370107,  1.00446972],
       [ 0.12589072, -0.7182046 , -1.28297761, -1.02388183],
       [ 0.47342794,  1.2541894 , -1.20791324,  0.43828727]])

In [98]:
from sklearn.preprocessing import Binarizer

Binarizer().fit_transform(MinMaxScaler().fit_transform(x))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
X_broken = np.array(X)

X_broken[:,::3] /= 4

X_broken

array([[1.275, 3.5  , 1.4  , 0.05 ],
       [1.225, 3.   , 1.4  , 0.05 ],
       [1.175, 3.2  , 1.3  , 0.05 ],
       [1.15 , 3.1  , 1.5  , 0.05 ],
       [1.25 , 3.6  , 1.4  , 0.05 ],
       [1.35 , 3.9  , 1.7  , 0.1  ],
       [1.15 , 3.4  , 1.4  , 0.075],
       [1.25 , 3.4  , 1.5  , 0.05 ],
       [1.1  , 2.9  , 1.4  , 0.05 ],
       [1.225, 3.1  , 1.5  , 0.025],
       [1.35 , 3.7  , 1.5  , 0.05 ],
       [1.2  , 3.4  , 1.6  , 0.05 ],
       [1.2  , 3.   , 1.4  , 0.025],
       [1.075, 3.   , 1.1  , 0.025],
       [1.45 , 4.   , 1.2  , 0.05 ],
       [1.425, 4.4  , 1.5  , 0.1  ],
       [1.35 , 3.9  , 1.3  , 0.1  ],
       [1.275, 3.5  , 1.4  , 0.075],
       [1.425, 3.8  , 1.7  , 0.075],
       [1.275, 3.8  , 1.5  , 0.075],
       [1.35 , 3.4  , 1.7  , 0.05 ],
       [1.275, 3.7  , 1.5  , 0.1  ],
       [1.15 , 3.6  , 1.   , 0.05 ],
       [1.275, 3.3  , 1.7  , 0.125],
       [1.2  , 3.4  , 1.9  , 0.05 ],
       [1.25 , 3.   , 1.6  , 0.05 ],
       [1.25 , 3.4  , 1.6  , 0.1  ],
       [1.3  , 3.5  , 1.5  , 0.05 ],
       [1.3  , 3.4  , 1.4  , 0.05 ],
       [1.175, 3.2  , 1.6  , 0.05 ],
       [1.2  , 3.1  , 1.6  , 0.05 ],
       [1.35 , 3.4  , 1.5  , 0.1  ],
       [1.3  , 4.1  , 1.5  , 0.025],
       [1.375, 4.2  , 1.4  , 0.05 ],
       [1.225, 3.1  , 1.5  , 0.05 ],
       [1.25 , 3.2  , 1.2  , 0.05 ],
       [1.375, 3.5  , 1.3  , 0.05 ],
       [1.225, 3.6  , 1.4  , 0.025],
       [1.1  , 3.   , 1.3  , 0.05 ],
       [1.275, 3.4  , 1.5  , 0.05 ],
       [1.25 , 3.5  , 1.3  , 0.075],
       [1.125, 2.3  , 1.3  , 0.075],
       [1.1  , 3.2  , 1.3  , 0.05 ],
       [1.25 , 3.5  , 1.6  , 0.15 ],
       [1.275, 3.8  , 1.9  , 0.1  ],
       [1.2  , 3.   , 1.4  , 0.075],
       [1.275, 3.8  , 1.6  , 0.05 ],
       [1.15 , 3.2  , 1.4  , 0.05 ],
       [1.325, 3.7  , 1.5  , 0.05 ],
       [1.25 , 3.3  , 1.4  , 0.05 ],
       [1.75 , 3.2  , 4.7  , 0.35 ],
       [1.6  , 3.2  , 4.5  , 0.375],
       [1.725, 3.1  , 4.9  , 0.375],
       [1.375, 2.3  , 4.   , 0.325],
       [1.625, 2.8  , 4.6  , 0.375],
       [1.425, 2.8  , 4.5  , 0.325],
       [1.575, 3.3  , 4.7  , 0.4  ],
       [1.225, 2.4  , 3.3  , 0.25 ],
       [1.65 , 2.9  , 4.6  , 0.325],
       [1.3  , 2.7  , 3.9  , 0.35 ],
       [1.25 , 2.   , 3.5  , 0.25 ],
       [1.475, 3.   , 4.2  , 0.375],
       [1.5  , 2.2  , 4.   , 0.25 ],
       [1.525, 2.9  , 4.7  , 0.35 ],
       [1.4  , 2.9  , 3.6  , 0.325],
       [1.675, 3.1  , 4.4  , 0.35 ],
       [1.4  , 3.   , 4.5  , 0.375],
       [1.45 , 2.7  , 4.1  , 0.25 ],
       [1.55 , 2.2  , 4.5  , 0.375],
       [1.4  , 2.5  , 3.9  , 0.275],
       [1.475, 3.2  , 4.8  , 0.45 ],
       [1.525, 2.8  , 4.   , 0.325],
       [1.575, 2.5  , 4.9  , 0.375],
       [1.525, 2.8  , 4.7  , 0.3  ],
       [1.6  , 2.9  , 4.3  , 0.325],
       [1.65 , 3.   , 4.4  , 0.35 ],
       [1.7  , 2.8  , 4.8  , 0.35 ],
       [1.675, 3.   , 5.   , 0.425],
       [1.5  , 2.9  , 4.5  , 0.375],
       [1.425, 2.6  , 3.5  , 0.25 ],
       [1.375, 2.4  , 3.8  , 0.275],
       [1.375, 2.4  , 3.7  , 0.25 ],
       [1.45 , 2.7  , 3.9  , 0.3  ],
       [1.5  , 2.7  , 5.1  , 0.4  ],
       [1.35 , 3.   , 4.5  , 0.375],
       [1.5  , 3.4  , 4.5  , 0.4  ],
       [1.675, 3.1  , 4.7  , 0.375],
       [1.575, 2.3  , 4.4  , 0.325],
       [1.4  , 3.   , 4.1  , 0.325],
       [1.375, 2.5  , 4.   , 0.325],
       [1.375, 2.6  , 4.4  , 0.3  ],
       [1.525, 3.   , 4.6  , 0.35 ],
       [1.45 , 2.6  , 4.   , 0.3  ],
       [1.25 , 2.3  , 3.3  , 0.25 ],
       [1.4  , 2.7  , 4.2  , 0.325],
       [1.425, 3.   , 4.2  , 0.3  ],
       [1.425, 2.9  , 4.2  , 0.325],
       [1.55 , 2.9  , 4.3  , 0.325],
       [1.275, 2.5  , 3.   , 0.275],
       [1.425, 2.8  , 4.1  , 0.325],
       [1.575, 3.3  , 6.   , 0.625],
       [1.45 , 2.7  , 5.1  , 0.475],
       [1.775, 3.   , 5.9  , 0.525],
       [1.575, 2.9  , 5.6  , 0.45 ],
       [1.625, 3.   , 5.8  , 0.55 ],
       [1.9  , 3.   , 6.6  , 0.525],
       [1.225, 2.5  , 4.5  , 0.425],
       [1.825, 2.9  , 6.3  , 0.45 ],
       [1.675, 2.5  , 5.8  , 0.45 ],
       [1.8  , 3.6  , 6.1  , 0.625],
       [1.625, 3.2  , 5.1  , 0.5  ],
       [1.6  , 2.7  , 5.3  , 0.475],
       [1.7  , 3.   , 5.5  , 0.525],
       [1.425, 2.5  , 5.   , 0.5  ],
       [1.45 , 2.8  , 5.1  , 0.6  ],
       [1.6  , 3.2  , 5.3  , 0.575],
       [1.625, 3.   , 5.5  , 0.45 ],
       [1.925, 3.8  , 6.7  , 0.55 ],
       [1.925, 2.6  , 6.9  , 0.575],
       [1.5  , 2.2  , 5.   , 0.375],
       [1.725, 3.2  , 5.7  , 0.575],
       [1.4  , 2.8  , 4.9  , 0.5  ],
       [1.925, 2.8  , 6.7  , 0.5  ],
       [1.575, 2.7  , 4.9  , 0.45 ],
       [1.675, 3.3  , 5.7  , 0.525],
       [1.8  , 3.2  , 6.   , 0.45 ],
       [1.55 , 2.8  , 4.8  , 0.45 ],
       [1.525, 3.   , 4.9  , 0.45 ],
       [1.6  , 2.8  , 5.6  , 0.525],
       [1.8  , 3.   , 5.8  , 0.4  ],
       [1.85 , 2.8  , 6.1  , 0.475],
       [1.975, 3.8  , 6.4  , 0.5  ],
       [1.6  , 2.8  , 5.6  , 0.55 ],
       [1.575, 2.8  , 5.1  , 0.375],
       [1.525, 2.6  , 5.6  , 0.35 ],
       [1.925, 3.   , 6.1  , 0.575],
       [1.575, 3.4  , 5.6  , 0.6  ],
       [1.6  , 3.1  , 5.5  , 0.45 ],
       [1.5  , 3.   , 4.8  , 0.45 ],
       [1.725, 3.1  , 5.4  , 0.525],
       [1.675, 3.1  , 5.6  , 0.6  ],
       [1.725, 3.1  , 5.1  , 0.575],
       [1.45 , 2.7  , 5.1  , 0.475],
       [1.7  , 3.2  , 5.9  , 0.575],
       [1.675, 3.3  , 5.7  , 0.625],
       [1.675, 3.   , 5.2  , 0.575],
       [1.575, 2.5  , 5.   , 0.475],
       [1.625, 3.   , 5.2  , 0.5  ],
       [1.55 , 3.4  , 5.4  , 0.575],
       [1.475, 3.   , 5.1  , 0.45 ]])

In [100]:
estimator = KNeighborsClassifier()

scores = cross_val_score(estimator, X_broken, y, scoring='accuracy')

scores.mean()

0.9466666666666667

In [101]:
from sklearn.pipeline import Pipeline

sequence = Pipeline([
    ('scale', MinMaxScaler()),
    ('estimate', KNeighborsClassifier())
])

scores = cross_val_score(sequence, X_broken, y, scoring='accuracy')

scores.mean()

0.96

In [102]:
import pandas as pd

games = pd.read_csv("../data/basketball/NBA_2016_games.csv", parse_dates=["Date"])

games.columns = ["DATE", "START", "VISITOR_TEAM", "VISITOR_POINTS", "HOME_TEAM", "HOME_POINTS", "BOX", "OT", "ATTEND", "ARENA", "NOTES"]

games

,DATE,START,VISITOR_TEAM,VISITOR_POINTS,HOME_TEAM,HOME_POINTS,BOX,OT,ATTEND,ARENA,NOTES
0,2015-10-27,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,United Center,NaN
1,2015-10-27,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,Philips Arena,NaN
2,2015-10-27,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,Oracle Arena,NaN
3,2015-10-28,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,Amway Center,NaN
4,2015-10-28,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,TD Garden,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1311,2016-06-08,9:00p,Golden State Warriors,90,Cleveland Cavaliers,120,Box Score,NaN,20562,Quicken Loans Arena,NaN
1312,2016-06-10,9:00p,Golden State Warriors,108,Cleveland Cavaliers,97,Box Score,NaN,20562,Quicken Loans Arena,NaN
1313,2016-06-13,9:00p,Cleveland Cavaliers,112,Golden State Warriors,97,Box Score,NaN,19596,Oracle Arena,NaN
1314,2016-06-16,9:00p,Golden State Warriors,101,Cleveland Cavaliers,115,Box Score,NaN,20562,Quicken Loans Arena,NaN
1315,2016-06-19,8:00p,Cleveland Cavaliers,93,Golden State Warriors,89,Box Score,NaN,19596,Oracle Arena,NaN

In [103]:
games["HOME_WIN"] = games["VISITOR_POINTS"] < games["HOME_POINTS"]

games.sample(5)

,DATE,START,VISITOR_TEAM,VISITOR_POINTS,HOME_TEAM,HOME_POINTS,BOX,OT,ATTEND,ARENA,NOTES,HOME_WIN
1027,2016-03-19,6:00p,Denver Nuggets,101,Charlotte Hornets,93,Box Score,NaN,19271,Time Warner Cable Arena,NaN,False
1214,2016-04-12,8:00p,Oklahoma City Thunder,98,San Antonio Spurs,102,Box Score,OT,18765,AT&T Center,NaN,True
180,2015-11-20,8:00p,Detroit Pistons,96,Minnesota Timberwolves,86,Box Score,NaN,13445,Target Center,NaN,False
521,2016-01-05,8:00p,Milwaukee Bucks,106,Chicago Bulls,117,Box Score,NaN,21686,United Center,NaN,True
1067,2016-03-24,7:00p,New Orleans Pelicans,84,Indiana Pacers,92,Box Score,NaN,17517,Bankers Life Fieldhouse,NaN,True

In [104]:
games["HOME_WIN"].mean()

0.5942249240121581

In [105]:
from collections import defaultdict

won_last = defaultdict(int)

for index, row in games.iterrows():

    home_team = row["HOME_TEAM"]
    visitor_team = row["VISITOR_TEAM"]

    games.at[index, "HOME_LAST_WIN"] = bool(won_last[home_team])
    games.at[index, "VISITOR_LAST_WIN"] = bool(won_last[visitor_team])

    if row["HOME_WIN"]:
        # print("WIN HOME: {} vs {}".format(home_team, visitor_team))
        won_last[home_team] = 1
        won_last[visitor_team] = 0
    else:
        # print("WIN VISITOR: {} vs {}".format(home_team, visitor_team))
        won_last[home_team] = 0
        won_last[visitor_team] = 1

games

,DATE,START,VISITOR_TEAM,VISITOR_POINTS,HOME_TEAM,HOME_POINTS,BOX,OT,ATTEND,ARENA,NOTES,HOME_WIN,HOME_LAST_WIN,VISITOR_LAST_WIN
0,2015-10-27,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,United Center,NaN,True,False,False
1,2015-10-27,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,Philips Arena,NaN,False,False,False
2,2015-10-27,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,Oracle Arena,NaN,True,False,False
3,2015-10-28,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,Amway Center,NaN,False,False,False
4,2015-10-28,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,TD Garden,NaN,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311,2016-06-08,9:00p,Golden State Warriors,90,Cleveland Cavaliers,120,Box Score,NaN,20562,Quicken Loans Arena,NaN,True,False,True
1312,2016-06-10,9:00p,Golden State Warriors,108,Cleveland Cavaliers,97,Box Score,NaN,20562,Quicken Loans Arena,NaN,False,True,False
1313,2016-06-13,9:00p,Cleveland Cavaliers,112,Golden State Warriors,97,Box Score,NaN,19596,Oracle Arena,NaN,False,True,False
1314,2016-06-16,9:00p,Golden State Warriors,101,Cleveland Cavaliers,115,Box Score,NaN,20562,Quicken Loans Arena,NaN,True,True,False
1315,2016-06-19,8:00p,Cleveland Cavaliers,93,Golden State Warriors,89,Box Score,NaN,19596,Oracle Arena,NaN,False,False,True

In [106]:
X = games[ ["HOME_LAST_WIN", "VISITOR_LAST_WIN"] ].values.astype(int)
y = games["HOME_WIN"].values.astype(int)

X, y

(array([[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [1, 0],
        [1, 0],
        [0, 1]]),
 array([1, 0, 1, ..., 0, 1, 0]))

In [107]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

scores = cross_val_score(DecisionTreeClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

59.42245650420554

In [108]:
standings = pd.read_csv("../data/basketball/NBA_2015_standings.csv")

standings

,Rk,Team,Overall,Home,Road,E,W,A,C,SE,...,Post,≤3,≥10,Oct,Nov,Dec,Jan,Feb,Mar,Apr
0,1,Golden State Warriors,67-15,39-2,28-13,25-5,42-10,9-1,7-3,9-1,...,25-6,5-3,45-9,1-0,13-2,11-3,12-3,8-3,16-2,6-2
1,2,Atlanta Hawks,60-22,35-6,25-16,38-14,22-8,12-6,14-4,12-4,...,17-11,6-4,30-10,0-1,9-5,14-2,17-0,7-4,9-7,4-3
2,3,Houston Rockets,56-26,30-11,26-15,23-7,33-19,9-1,8-2,6-4,...,20-9,8-4,31-14,2-0,11-4,9-5,11-6,7-3,10-6,6-2
3,4,Los Angeles Clippers,56-26,30-11,26-15,19-11,37-15,7-3,6-4,6-4,...,21-7,3-5,33-9,2-0,9-5,11-6,11-4,5-6,11-5,7-0
4,5,Memphis Grizzlies,55-27,31-10,24-17,20-10,35-17,8-2,5-5,7-3,...,16-13,9-3,26-13,2-0,13-2,8-6,12-4,7-4,9-8,4-3
5,6,San Antonio Spurs,55-27,33-8,22-19,23-7,32-20,7-3,7-3,9-1,...,21-8,6-7,34-7,1-1,11-3,8-10,10-4,6-5,12-3,7-1
6,7,Cleveland Cavaliers,53-29,31-10,22-19,35-17,18-12,12-6,11-5,12-6,...,20-7,6-4,30-14,1-1,7-6,10-7,11-6,8-3,11-4,5-2
7,8,Portland Trail Blazers,51-31,32-9,19-22,20-10,31-21,8-2,7-3,5-5,...,15-14,5-1,30-11,1-1,12-3,13-3,6-9,6-3,10-6,3-6
8,9,Chicago Bulls,50-32,27-14,23-18,33-19,17-13,16-2,8-8,9-9,...,16-12,7-2,20-16,1-1,10-5,11-4,8-9,7-3,8-7,5-3
9,10,Dallas Mavericks,50-32,27-14,23-18,21-9,29-23,9-1,5-5,7-3,...,14-13,5-4,22-18,1-1,12-4,10-5,9-7,7-5,6-7,5-3
10,11,Toronto Raptors,49-33,27-14,22-19,33-19,16-14,11-5,8-10,14-4,...,13-16,6-5,29-11,1-0,12-4,11-4,9-7,4-7,7-8,5-3
11,12,Washington Wizards,46-36,29-12,17-24,30-22,16-14,11-7,9-9,10-6,...,13-15,9-4,21-14,1-1,9-4,12-4,9-8,3-9,7-7,5-3
12,13,New Orleans Pelicans,45-37,28-13,17-24,16-14,29-23,6-4,5-5,5-5,...,18-11,10-4,19-14,1-0,6-8,9-8,9-6,6-5,8-7,6-3
13,14,Oklahoma City Thunder,45-37,29-12,16-25,20-10,25-27,6-4,5-5,9-1,...,17-12,4-8,26-14,0-2,5-10,11-5,7-7,9-3,10-5,3-5
14,15,Milwaukee Bucks,41-41,23-18,18-23,30-22,11-19,14-4,7-9,9-9,...,11-18,5-9,17-16,1-1,9-7,7-8,8-6,7-5,4-11,5-3
15,16,Boston Celtics,40-42,21-20,19-22,28-24,12-18,12-4,9-9,7-11,...,20-11,8-6,17-14,1-0,3-10,7-8,5-11,7-4,10-8,7-1
16,17,Phoenix Suns,39-43,22-19,17-24,18-12,21-31,8-2,6-4,4-6,...,10-18,4-12,14-19,2-0,8-8,8-8,10-5,3-8,7-8,1-6
17,18,Brooklyn Nets,38-44,19-22,19-22,24-28,14-16,10-6,7-11,7-11,...,17-13,10-2,15-23,0-1,6-8,9-7,3-12,6-5,9-7,5-4
18,19,Indiana Pacers,38-44,23-18,15-26,28-24,10-20,9-9,8-8,11-7,...,17-11,4-12,19-20,1-1,6-9,5-11,5-11,7-2,8-8,6-2
19,20,Utah Jazz,38-44,21-20,17-24,15-15,23-29,6-4,6-4,3-7,...,19-10,5-10,18-19,0-2,5-10,6-9,6-9,6-5,10-6,5-3
20,21,Miami Heat,37-45,20-21,17-24,25-27,12-18,14-4,5-13,6-10,...,15-15,4-10,15-28,1-0,8-7,5-12,6-7,5-7,9-7,3-5
21,22,Charlotte Hornets,33-49,19-22,14-27,25-27,8-22,10-8,7-11,8-8,...,11-19,6-8,13-22,1-0,3-14,6-9,10-4,3-6,8-9,2-7
22,23,Detroit Pistons,32-50,18-23,14-27,23-29,9-21,8-10,6-10,9-9,...,11-17,7-6,19-25,0-2,3-12,5-9,10-7,5-6,6-9,3-5
23,24,Denver Nuggets,30-52,19-22,11-30,11-19,19-33,1-9,6-4,4-6,...,10-19,4-4,17-28,1-0,7-8,5-11,6-10,1-9,8-8,2-6
24,25,Sacramento Kings,29-53,18-23,11-30,11-19,18-34,4-6,4-6,3-7,...,11-19,6-4,12-28,1-1,8-7,4-11,4-10,3-7,6-11,3-6
25,26,Orlando Magic,25-57,13-28,12-29,15-37,10-20,6-12,5-13,4-12,...,8-18,6-8,4-27,0-2,7-10,6-10,2-13,4-6,3-11,3-5
26,27,Los Angeles Lakers,21-61,12-29,9-32,12-18,9-43,4-6,5-5,3-7,...,8-21,6-6,5-30,0-3,4-10,6-9,3-12,3-7,4-12,1-8
27,28,Philadelphia 76ers,18-64,12-29,6-35,12-40,6-24,2-14,5-13,5-13,...,6-23,3-7,5-41,0-2,0-14,4-10,6-12,3-7,5-12,0-7
28,29,New York Knicks,17-65,10-31,7-34,11-41,6-24,5-11,2-16,4-14,...,7-22,2-7,3-39,1-1,3-13,1-15,4-9,3-8,2-14,3-5
29,30,Minnesota Timberwolves,16-66,9-32,7-34,9-21,7-45,4-6,3-7,2-8,...,5-24,6-6,4-40,1-1,3-10,1-14,3-14,5-6,3-13,0-8

In [109]:
for index, row in games.iterrows():

    home_team = row["HOME_TEAM"]
    visitor_team = row["VISITOR_TEAM"]

    home_rank = standings[ (standings["Team"] == home_team) ]["Rk"].values[0]
    visitor_rank = standings[ (standings["Team"] == visitor_team) ]["Rk"].values[0]

    games.at[index, "HOME_RANK"] = home_rank
    games.at[index, "VISITOR_RANK"] = visitor_rank
    games.at[index, "HOME_RANK_HIGHER"] = home_rank < visitor_rank

games

,DATE,START,VISITOR_TEAM,VISITOR_POINTS,HOME_TEAM,HOME_POINTS,BOX,OT,ATTEND,ARENA,NOTES,HOME_WIN,HOME_LAST_WIN,VISITOR_LAST_WIN,HOME_RANK,VISITOR_RANK,HOME_RANK_HIGHER
0,2015-10-27,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,United Center,NaN,True,False,False,9.0,7.0,False
1,2015-10-27,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,Philips Arena,NaN,False,False,False,2.0,23.0,True
2,2015-10-27,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,Oracle Arena,NaN,True,False,False,1.0,13.0,True
3,2015-10-28,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,Amway Center,NaN,False,False,False,26.0,12.0,False
4,2015-10-28,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,TD Garden,NaN,True,False,False,16.0,28.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311,2016-06-08,9:00p,Golden State Warriors,90,Cleveland Cavaliers,120,Box Score,NaN,20562,Quicken Loans Arena,NaN,True,False,True,7.0,1.0,False
1312,2016-06-10,9:00p,Golden State Warriors,108,Cleveland Cavaliers,97,Box Score,NaN,20562,Quicken Loans Arena,NaN,False,True,False,7.0,1.0,False
1313,2016-06-13,9:00p,Cleveland Cavaliers,112,Golden State Warriors,97,Box Score,NaN,19596,Oracle Arena,NaN,False,True,False,1.0,7.0,True
1314,2016-06-16,9:00p,Golden State Warriors,101,Cleveland Cavaliers,115,Box Score,NaN,20562,Quicken Loans Arena,NaN,True,True,False,7.0,1.0,False
1315,2016-06-19,8:00p,Cleveland Cavaliers,93,Golden State Warriors,89,Box Score,NaN,19596,Oracle Arena,NaN,False,False,True,1.0,7.0,True

In [110]:
X = games[ ["HOME_LAST_WIN", "VISITOR_LAST_WIN", "HOME_RANK_HIGHER"] ].values.astype(int)
y = games["HOME_WIN"].values.astype(int)

X, y

(array([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        ...,
        [1, 0, 1],
        [1, 0, 0],
        [0, 1, 1]]),
 array([1, 0, 1, ..., 0, 1, 0]))

In [111]:
scores = cross_val_score(DecisionTreeClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

61.77670238506741

In [112]:
last_winner_match_teams =defaultdict(str)

for index, row in games.iterrows():

    home_team = row["HOME_TEAM"]
    visitor_team = row["VISITOR_TEAM"]

    match_team = tuple(sorted([home_team, visitor_team]))

    home_win_last_match = False

    if last_winner_match_teams[match_team] == home_team:
        home_win_last_match = True

    games.at[index, "HOME_WIN_LAST_MATCH"] = home_win_last_match

    winner = visitor_team

    if row["HOME_WIN"]:
        winner = home_team

    last_winner_match_teams[match_team] = winner

games

,DATE,START,VISITOR_TEAM,VISITOR_POINTS,HOME_TEAM,HOME_POINTS,BOX,OT,ATTEND,ARENA,NOTES,HOME_WIN,HOME_LAST_WIN,VISITOR_LAST_WIN,HOME_RANK,VISITOR_RANK,HOME_RANK_HIGHER,HOME_WIN_LAST_MATCH
0,2015-10-27,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,United Center,NaN,True,False,False,9.0,7.0,False,False
1,2015-10-27,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,Philips Arena,NaN,False,False,False,2.0,23.0,True,False
2,2015-10-27,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,Oracle Arena,NaN,True,False,False,1.0,13.0,True,False
3,2015-10-28,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,Amway Center,NaN,False,False,False,26.0,12.0,False,False
4,2015-10-28,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,TD Garden,NaN,True,False,False,16.0,28.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311,2016-06-08,9:00p,Golden State Warriors,90,Cleveland Cavaliers,120,Box Score,NaN,20562,Quicken Loans Arena,NaN,True,False,True,7.0,1.0,False,False
1312,2016-06-10,9:00p,Golden State Warriors,108,Cleveland Cavaliers,97,Box Score,NaN,20562,Quicken Loans Arena,NaN,False,True,False,7.0,1.0,False,True
1313,2016-06-13,9:00p,Cleveland Cavaliers,112,Golden State Warriors,97,Box Score,NaN,19596,Oracle Arena,NaN,False,True,False,1.0,7.0,True,True
1314,2016-06-16,9:00p,Golden State Warriors,101,Cleveland Cavaliers,115,Box Score,NaN,20562,Quicken Loans Arena,NaN,True,True,False,7.0,1.0,False,True
1315,2016-06-19,8:00p,Cleveland Cavaliers,93,Golden State Warriors,89,Box Score,NaN,19596,Oracle Arena,NaN,False,False,True,1.0,7.0,True,False

In [113]:
X = games[ ["HOME_LAST_WIN", "VISITOR_LAST_WIN", "HOME_RANK_HIGHER", "HOME_WIN_LAST_MATCH"] ].values.astype(int)
y = games["HOME_WIN"].values.astype(int)

X, y

(array([[0, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        ...,
        [1, 0, 1, 1],
        [1, 0, 0, 1],
        [0, 1, 1, 0]]),
 array([1, 0, 1, ..., 0, 1, 0]))

In [114]:
scores = cross_val_score(DecisionTreeClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

62.386219610554214

In [115]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(random_state=14), X, y, scoring='accuracy')

100 * scores.mean()

62.46226523793064

In [117]:
from sklearn.model_selection import GridSearchCV

parameter_space = {
    "max_features": [2, 10],
    "n_estimators": [100, 200],
    "criterion": ["gini", "entropy"],
    "min_samples_leaf": [2, 4, 6]
}

estimator = RandomForestClassifier(random_state=14)

grid = GridSearchCV(estimator, parameter_space)

scores = cross_val_score(grid, X, y, scoring='accuracy')

100 * scores.mean()

62.46226523793064

In [1]:
import pandas as pd

ratings = pd.read_csv("../data/ml-latest-small/ratings.csv")

ratings.sample(5)

       userId  movieId  rating   timestamp
91412     593      593     4.0  1181007635
35966     245     3252     3.0   951183441
62242     413      527     5.0  1484439759
91046     590     5266     2.5  1267150640
84912     551   112852     3.0  1504320843

In [2]:
ratings["favorable"] = ratings["rating"] > 3

ratings.sample(5)

       userId  movieId  rating   timestamp  favorable
67007     432    57274     5.0  1316391360       True
57717     380    45666     2.0  1494696322      False
96095     602      761     3.0   840876597      False
82105     520     4306     4.0  1326609180       True
76773     480     5943     1.5  1179166136      False

In [7]:
ratings_200 = ratings[ (ratings["userId"].isin(range(200))) ]

ratings_200.sample(5)

       userId  movieId  rating   timestamp  favorable
26839     182     4896     4.0  1054782973       True
11787      72     1196     4.5  1217324882       True
13895      89   103602     5.0  1520408944       True
22266     149     1676     5.0   902084966       True
12979      83     1225     5.0  1332840366       True

In [15]:
favorable_ratings = ratings_200[ (ratings_200["favorable"]) ].groupby("userId")["movieId"]

favorable_reviews_by_user = dict((userId, movies.values) for userId, movies in favorable_ratings)

favorable_reviews_by_user

{1: array([   1,    3,    6,   47,   50,  101,  110,  151,  157,  163,  216,
         231,  235,  260,  333,  349,  356,  362,  367,  441,  457,  480,
         527,  543,  552,  553,  590,  592,  593,  596,  608,  661,  733,
         804,  919,  923,  940,  943,  954, 1023, 1024, 1025, 1029, 1031,
        1032, 1042, 1049, 1060, 1073, 1080, 1089, 1090, 1092, 1097, 1127,
        1136, 1196, 1197, 1198, 1206, 1208, 1210, 1213, 1214, 1220, 1222,
        1224, 1226, 1240, 1256, 1265, 1270, 1275, 1278, 1282, 1291, 1298,
        1348, 1473, 1500, 1517, 1552, 1573, 1587, 1617, 1620, 1625, 1732,
        1777, 1793, 1804, 1805, 1920, 1927, 1954, 1967, 2000, 2005, 2012,
        2018, 2028, 2033, 2046, 2048, 2054, 2058, 2078, 2090, 2094, 2096,
        2099, 2105, 2115, 2116, 2137, 2139, 2141, 2143, 2161, 2174, 2193,
        2268, 2273, 2291, 2329, 2353, 2366, 2387, 2395, 2406, 2427, 2450,
        2459, 2470, 2478, 2492, 2502, 2529, 2542, 2571, 2580, 2596, 2616,
        2628, 2640, 2641, 2644, 2648, 2654, 2692, 2700, 2716, 2761, 2797,
        2826, 2858, 2872, 2899, 2916, 2944, 2947, 2948, 2949, 2959, 2985,
        2987, 2991, 2993, 2997, 3033, 3034, 3052, 3053, 3062, 3147, 3168,
        3253, 3273, 3386, 3439, 3440, 3441, 3448, 3450, 3479, 3489, 3527,
        3578, 3617, 3639, 3671, 3702, 3703, 3729, 3740, 3744, 3793, 3809,
        4006, 5060], dtype=int64),
 2: array([   333,   1704,   3578,   6874,   8798,  46970,  48516,  58559,
         60756,  68157,  74458,  79132,  80489,  80906,  86345,  89774,
         91529,  99114, 106782, 112552, 115713, 122882, 131724],
       dtype=int64),
 3: array([  849,  1275,  1587,  2288,  2851,  3024,  3703,  4518,  5181,
         5746,  5764,  5919,  6835,  7899,  7991, 26409, 70946],
       dtype=int64),
 4: array([ 106,  125,  162,  176,  215,  232,  260,  265,  319,  342,  345,
         348,  368,  457,  475,  492,  538,  588,  593,  608,  708,  800,
         892,  898,  899,  902,  904,  908,  910,  912,  914,  919,  920,
         930, 1025, 1046, 1073, 1077, 1080, 1084, 1086, 1103, 1136, 1179,
        1188, 1196, 1197, 1203, 1213, 1219, 1225, 1250, 1259, 1265, 1266,
        1282, 1283, 1288, 1291, 1449, 1466, 1500, 1517, 1641, 1719, 1732,
        1733, 1834, 1883, 1895, 1914, 1947, 1967, 1968, 2076, 2078, 2109,
        2150, 2174, 2186, 2203, 2204, 2351, 2359, 2390, 2406, 2467, 2583,
        2599, 2683, 2692, 2762, 2791, 2843, 2858, 2874, 2921, 2926, 2997,
        3033, 3044, 3060, 3083, 3160, 3176, 3204, 3255, 3317, 3365, 3386,
        3408, 3508, 3851, 3897, 3967, 3996, 4021, 4033, 4034, 4121, 4239,
        4246, 4273, 4347, 4765, 4896, 4902, 4967], dtype=int64),
 5: array([  1,  21,  34,  36,  50,  58, 110, 232, 247, 261, 290, 296, 367,
        457, 474, 475, 527, 531, 588, 590, 594, 595, 596], dtype=int64),
 6: array([   2,    3,    5,    6,    7,   11,   15,   16,   17,   22,   24,
          26,   32,   34,   36,   41,   43,   46,   47,   54,   60,   61,
          62,   76,   86,   89,   92,   93,   95,  104,  110,  112,  141,
         145,  146,  150,  151,  158,  160,  168,  195,  207,  210,  212,
         216,  222,  225,  230,  236,  237,  248,  250,  252,  257,  261,
         262,  271,  274,  276,  277,  281,  292,  304,  314,  315,  316,
         317,  318,  329,  333,  337,  339,  340,  349,  350,  351,  353,
         354,  355,  356,  361,  364,  367,  368,  370,  377,  380,  415,
         432,  434,  440,  450,  454,  457,  468,  469,  474,  475,  477,
         480,  491,  500,  508,  515,  516,  542,  553,  569,  587,  588,
         590,  593,  594,  595,  597,  609,  616,  631,  637,  647,  700,
         708,  709,  711,  736,  780,  783,  802,  830,  835,  838,  848,
         852,  986,  991,  996, 1004, 1006, 1049, 1061, 1064, 1082],
       dtype=int64),
 7: array([    1,    50,   150,   165,   260,   356,   466,   480,   593,
          595,   648,   750,   780,   924,  1101,  1196,  1208,  1210,
         1219,  1220,  1240,  1270,  1517,  1584,  1610,  1917,  1954,
         2019,  2353,  2529,  2671,  2717,  2762,  2858,  3114,  3408,
         3793,  3869,  3916,  4018,  4306,  4370,  4886,  4896,  4963,
         4993,  4995,  5218,  5349,  5445,  5618,  5816,  5952,  5989,
         5991,  6333,  6365,  6539,  6863,  7143,  7153,  7445,  8207,
         8360,  8528,  8636,  8665,  8798,  8870,  8908,  8949,  8957,
         8958,  8961,  8984, 30812, 31878, 32587, 33162, 34319, 37741,
        38388, 42002, 45499, 45517, 48783, 49272, 49278], dtype=int64),
 8: array([  2,  11,  21,  34,  47,  50, 150, 185, 186, 231, 253, 296, 318,
        357, 364, 377, 380, 454, 480, 527, 590, 593], dtype=int64),
 9: array([ 223,  922,  923, 1095, 1198, 1270, 1674, 2012, 2300, 4993, 5218,
        5445, 5447, 5451, 5481, 5890, 5893, 5902, 5952, 5956, 5965, 6001],
       dtype=int64),
 10: array([   356,    588,    597,    912,   1784,   1907,   2671,   3578,
          4246,   4306,   4447,   4993,   4995,   5377,   5952,   6377,
          6535,   6942,   7149,   7153,   7154,   7169,   7293,   7375,
          7451,   7458,   8529,   8533,   8636,   8665,   8869,   8969,
         30749,  31685,  33794,  40819,  49272,  49286,  51705,  54286,
         56367,  58047,  58559,  63113,  63992,  66203,  68954,  69406,
         71579,  72330,  72720,  72737,  79091,  80549,  81845,  81847,
         82167,  84374,  87222,  88163,  91529,  92259,  94070,  95167,
         95449,  95543,  96079, 103335, 103339, 104374, 106489, 106696,
        109853, 112006, 113275, 113394, 129428, 136020, 137595, 140110],
       dtype=int64),
 11: array([   6,   36,  110,  150,  170,  292,  318,  349,  356,  380,  457,
         474,  480,  511,  529,  589,  593,  648,  733,  736,  780, 1101,
        1210, 1358, 1408, 1518, 1552, 1584, 1586, 1597, 1604, 1608, 1693,
        1704, 1721, 1784, 1840, 1917, 1918, 1923, 2028], dtype=int64),
 12: array([   39,   168,   222,   256,   261,   357,   543,   830,   838,
          920,  1265,  1357,  1721,  1876,  2072,  2100,  2485,  2572,
         2581,  2694,  2717,  3668,  3967,  4018,  5620,  6942,  8533,
        40629, 63992], dtype=int64),
 13: array([  47, 1198, 1590, 1639, 1721, 2571, 3300, 3578, 3624, 3753, 3793,
        3798, 3827, 3863, 3897, 3996, 4011, 4148], dtype=int64),
 14: array([ 25,  32,  47,  95, 110, 150, 266, 282, 288, 337, 339, 356, 376,
        383, 434, 477, 509, 539, 553, 590, 593], dtype=int64),
 15: array([    47,    260,    296,    318,    356,    527,    589,    780,
           858,   1196,   1198,   1200,   1210,   1214,   1240,   1265,
          1270,   1653,   2001,   2011,   2012,   2028,   2150,   2329,
          2571,   2858,   2916,   3147,   3156,   3499,   3510,   3535,
          3555,   3578,   3949,   4018,   4022,   4370,   4720,   4886,
          4993,   4995,   5445,   5952,   5989,   6502,   7254,   8644,
         33493,  48304,  48780,  56174,  60069,  64614,  68954,  69757,
         70286,  71057,  79132,  84152,  84954,  85414,  97938, 101864,
        103249, 104841, 105504, 109487, 111759, 112556, 122886, 134130,
        134853, 152077, 158872, 160980, 166528, 166635], dtype=int64),
 16: array([   47,    50,   111,   293,   318,   319,   356,   527,   541,
          608,   678,   745,   750,   849,   904,   912,   913,   923,
         1089,  1136,  1147,  1148,  1186,  1193,  1197,  1198,  1199,
         1203,  1207,  1208,  1213,  1214,  1222,  1223,  1230,  1247,
         1252,  1260,  1261,  1267,  1276,  1299,  1617,  1680,  1704,
         2019,  2109,  2329,  2571,  2707,  2723,  2762,  2858,  2959,
         3000,  3022,  3108,  3174,  3429,  3683,  3741,  3949,  4002,
         4226,  4878,  4973,  4993,  5618,  5782,  5952,  5971,  6350,
         7099,  7153,  7361, 27611, 27773, 48394, 58559, 60069, 68954,
        78499, 91529], dtype=int64),
 17: array([    1,    44,    47,    50,   110,   111,   150,   260,   293,
          296,   318,   356,   480,   527,   541,   589,   590,   592,
          593,   750,   780,   858,   899,   904,   910,  1032,  1036,
         1089,  1090,  1093,  1100,  1193,  1196,  1197,  1198,  1201,
         1206,  1209,  1210,  1213,  1221,  1222,  1228,  1234,  1240,
         1252,  1258,  1259,  1263,  1270,  1291,  1375,  1405,  1732,
         1967,  2005,  2019,  2028,  2194,  2329,  2502,  2571,  2717,
         2762,  2858,  2959,  3039,  3147,  3263,  3435,  3508,  3681,
         3702,  3949,  4226,  4571,  4993,  5618,  5782,  5952,  5971,
         6016,  6350,  6870,  7099,  7153,  7482, 27773, 31658, 33794,
        48394, 48516, 58559, 60069, 64839, 68157, 68358, 77455, 78499,
        79132, 80463, 81932, 82459], dtype=int64),
 18: array([     1,      6,     16,     32,     36,     47,     50,     70,
           110,    111,    145,    163,    165,    180,    223,    235,
           260,    288,    293,    296,    318,    329,    337,    356,
           431,    457,    480,    500,    508,    527,    541,    555,
           586,    588,    589,    590,    593,    608,    628,    745,
           778,    780,    849,    858,    904,    908,    913,    919,
           923,    924,   1020,   1036,   1059,   1080,   1086,   1089,
          1095,   1136,   1148,   1193,   1196,   1198,   1201,   1203,
          1206,   1207,   1208,   1209,   1210,   1212,   1213,   1214,
          1219,   1221,   1222,   1223,   1227,   1234,   1240,   1245,
          1246,   1247,   1252,   1260,   1270,   1275,   1276,   1291,
          1356,   1370,   1371,   1374,   1375,   1466,   1527,   1544,
          1580,   1617,   1625,   1653,   1676,   1704,   1721,   1729,
          1732,   1784,   1805,   1892,   1918,   1954,   1961,   2000,
          2001,   2002,   2011,   2019,   2028,   2058,   2115,   2194,
          2268,   2278,   2291,   2324,   2329,   2409,   2410,   2420,
          2490,   2542,   2571,   2706,   2762,   2918,   2951,   2959,
          2997,   3052,   3081,   3147,   3275,   3462,   3578,   3681,
          3702,   3751,   3793,   3896,   3949,   4007,   4011,   4226,
          4239,   4262,   4306,   4327,   4383,   4886,   4896,   4963,
          4973,   4993,   4995,   5008,   5120,   5218,   5266,   5349,
          5418,   5445,   5464,   5574,   5608,   5669,   5679,   5816,
          5903,   5952,   5956,   5989,   5995,   6300,   6333,   6365,
          6373,   6377,   6440,   6539,   6787,   6807,   6863,   6870,
          6874,   7018,   7147,   7153,   7254,   7361,   7373,   7438,
          7753,   7843,   8117,   8360,   8368,   8644,   8665,   8784,
          8798,   8917,   8950,   8957,   8958,   8961,  26444,  26614,
         27716,  27773,  27831,  27878,  30793,  30812,  32460,  32587,
         33615,  33794,  34150,  34405,  36529,  37729,  37733,  37741,
         38038,  38061,  40819,  44022,  44191,  44199,  44555,  44665,
         45499,  45517,  45722,  46578,  47491,  48394,  48516,  48780,
         49651,  50872,  51357,  51540,  51662,  52604,  53125,  54272,
         54286,  55118,  55247,  55276,  55290,  55765,  56757,  57640,
         57669,  58295,  58299,  58559,  59315,  59784,  60040,  60684,
         62434,  63131,  64197,  64614,  64839,  64957,  65596,  66934,
         67255,  68073,  68157,  68159,  68319,  68358,  68954,  69640,
         69757,  69951,  70286,  71108,  71899,  72011,  72998,  73017,
         73268,  73321,  73323,  73499,  74458,  74510,  74789,  74948,
         76251,  77561,  78499,  79132,  79695,  79702,  80219,  80489,
         81788,  84392,  85354,  85414,  86190,  86332,  86628,  87232,
         88140,  89745,  90600,  91485,  91500,  91529,  91542,  91658,
         92094,  96432,  96488,  96655,  97752,  98124,  98585,  98809,
         99114,  99728,  99813, 102125, 102445, 102903, 103253, 103772,
        106072, 106487, 106489, 106839, 107846, 109374, 109487, 110102,
        111362, 111759, 112183, 112334, 112421, 112552, 112852, 114060,
        114066, 115713, 116797, 116823, 117176, 118900, 119145, 122886,
        122892, 122900, 122904, 122918, 122924, 122926, 128620, 134130,
        134853, 135569, 139385, 140289, 141688, 142488, 144210, 145283,
        148626, 150548, 155168, 157108, 157110, 158238, 158972, 159093,
        161582, 162350, 162606, 166015, 166635, 168252, 171023, 176101,
        177593, 180777, 185135], dtype=int64),
 19: array([   1,   32,   34,  235,  260,  293,  353,  357,  367,  377,  457,
         541,  551,  589,  592,  674,  720,  724,  745,  783,  818,  837,
         852,  903,  904,  910,  913,  931,  933, 1073, 1079, 1086, 1097,
        1148, 1193, 1196, 1197, 1198, 1214, 1219, 1234, 1240, 1256, 1265,
        1269, 1270, 1278, 1285, 1291, 1297, 1372, 1374, 1376, 1527, 1566,
        1573, 1617, 1625, 1653, 1658, 1923, 1967, 2005, 2037, 2041, 2081,
        2094, 2137, 2140, 2174, 2186, 2253, 2359, 2371, 2396, 2423, 2491,
        2571, 2606, 2700, 2716, 2723, 2762, 2763, 2858, 2918, 2936, 2959,
        2968, 2987, 2997, 3035, 3056, 3070, 3108, 3175, 3213, 3358, 3396,
        3421, 3471, 3477, 3745, 3754, 3793], dtype=int64),
 20: array([  13,   34,   48,  107,  239,  262,  317,  362,  364,  531,  551,
         588,  594,  595,  596,  661,  720,  783,  837,  899,  914,  919,
         986, 1012, 1013, 1015, 1018, 1022, 1025, 1028, 1029, 1032, 1035,
        1073, 1088, 1097, 1148, 1282, 1333, 1380, 1489, 1566, 1688, 1907,
        1919, 1947, 2005, 2018, 2033, 2048, 2059, 2078, 2080, 2081, 2083,
        2085, 2087, 2089, 2096, 2100, 2135, 2137, 2140, 2141, 2161, 2294,
        2300, 2355, 2394, 2565, 2657, 2687, 2700, 2709, 2746, 2761, 2804,
        2857, 2941, 2987, 3034, 3114, 3159, 3189, 3301, 3396, 3397, 3398,
        3408, 3410, 3438, 3483, 3549, 3578, 3751, 3755, 3793, 3852, 3897,
        3948, 3967, 3977, 3988, 3996, 4014, 4016, 4019, 4022, 4025, 4027,
        4029, 4039, 4090, 4154, 4161, 4226, 4246, 4299, 4306, 4308, 4310,
        4344, 4378, 4446, 4519, 4700, 4720, 4776, 4783, 4816, 4886, 4896,
        4901, 4979, 4990, 4993, 4995, 5013, 5014, 5015, 5103, 5218, 5293,
        5299, 5364, 5378, 5388, 5445, 5618, 5630, 5679, 5693, 5785, 5816,
        5952, 5989, 5991, 6143, 6170, 6297, 6333, 6345, 6358, 6365],
       dtype=int64),
 21: array([     1,      2,     10,    165,    260,    296,    355,    356,
           364,    370,    480,    541,    588,    589,    592,    597,
           648,    719,    733,    743,    780,   1036,   1196,   1198,
          1210,   1240,   1265,   1270,   1291,   1370,   1544,   1580,
          1704,   1721,   1722,   1918,   2000,   2002,   2011,   2012,
          2115,   2167,   2273,   2376,   2424,   2529,   2541,   2571,
          2617,   2628,   2671,   2706,   2716,   2717,   2763,   2916,
          2947,   2948,   2949,   2985,   2989,   2990,   2991,   2993,
          3022,   3082,   3114,   3253,   3489,   3623,   3633,   3635,
          3638,   3639,   3793,   3868,   3869,   3948,   3984,   4005,
          4085,   4306,   4446,   4489,   4545,   4638,   4701,   4718,
          4886,   4896,   4963,   5218,   5378,   5418,   5445,   5459,
          5574,   5816,   5872,   5989,   6155,   6365,   6503,   6539,
          6548,   6934,   6942,   7143,   7569,   7570,   7573,   8360,
          8368,   8529,   8644,   8665,   8798,   8961,   8972,   8984,
         30793,  30825,  31433,  31685,  32296,  33004,  33493,  33615,
         33679,  33794,  34048,  36519,  40815,  44022,  45186,  45447,
         45499,  46972,  47566,  47997,  49272,  49286,  50872,  51084,
         51662,  52973,  53121,  53125,  53322,  53996,  54276,  54286,
         56775,  58559,  58998,  59315,  59615,  59784,  60074,  60397,
         63082,  63113,  63859,  68791,  68793,  68954,  69122,  69406,
         69526,  69644,  69844,  70286,  72378,  72998,  73321,  76093,
         77561,  78469,  78499,  78637,  79132,  79185,  79293,  79592,
         81229,  81845,  82202,  84152,  85259,  87232,  87520,  88125,
         88140,  89745,  90249,  91500,  91529,  91535,  91630,  94677,
         94777,  95167,  95170,  95441,  95510,  96079,  96588,  97938,
         98124,  99114, 101864, 102125, 102481, 103141, 103228, 103335,
        103339, 103372, 103384, 103810, 103883, 104211, 104374, 104841,
        105653, 105954, 106072, 106487, 106491, 106696, 106918, 107141,
        108190, 109374, 109723, 110102, 110130, 111362, 111617, 111743,
        111759, 111781, 111844, 112006, 112138, 112175, 112852, 114180,
        115149, 115502, 115617, 115877, 116823, 117368, 117529, 117590,
        117922, 119145, 119155, 122882, 122886, 122892, 122896, 122900,
        122904, 122922, 134368, 134853, 135133, 135536, 135887, 136020,
        138036, 143385, 152081, 164179, 164909, 166492, 167036, 168248],
       dtype=int64),
 22: array([  107,   216,   253,   318,   356,   541,  1193,  1223,  1952,
         1953,  2160,  2300,  2541,  2959,  3006,  3210,  3489,  3578,
         3751,  3911,  3996,  4017,  4034,  4036,  4848,  4886,  4903,
         4979,  4995,  5418,  5617,  5669,  5902,  6377,  6711,  6870,
         6874,  7361,  7438,  8798,  8961,  8970, 37741, 48780, 49272,
        54503, 55820, 56782, 64575, 68157, 68536, 72998], dtype=int64),
 23: array([   6,   29,   32,   50,  272,  293,  296,  334,  541,  608,  741,
         778,  858,  904,  912,  913,  923,  924, 1050, 1080, 1089, 1175,
        1193, 1199, 1206, 1208, 1212, 1214, 1217, 1218, 1221, 1222, 1232,
        1233, 1237, 1243, 1245, 1249, 1252, 1258, 1266, 1274, 1284, 1464,
        1617, 1711, 1748, 1809, 1859, 2467, 2579, 2686, 2726, 2761, 2912,
        3000, 3108, 3181, 3265, 3681, 3822, 3949, 3996, 4226, 4235, 4973,
        5333, 5618, 5782, 5971, 6234, 6440, 6773, 6790, 6807, 6857, 6989,
        7064, 7099, 7123, 7587, 7924, 8012, 8228, 8370], dtype=int64),
 24: array([     6,     32,     50,    165,    253,    296,    316,    318,
           356,    457,    552,    593,    608,    780,   1197,   1198,
          1220,   1246,   1265,   1370,   1396,   1527,   1580,   1663,
          1682,   1704,   1784,   2028,   2115,   2273,   2421,   2424,
          2571,   2617,   2686,   2916,   3147,   3578,   4027,   4262,
          4299,   4489,   4701,   4855,   4973,   4995,   5064,   5418,
          5673,   5791,   6350,   7143,   7293,  27773,  31685,  33679,
         34437,  35836,  38061,  44191,  46976,  49272,  51662,  52973,
         54286,  57368,  58559,  58998,  59615,  61024,  64957,  68358,
         70286,  72011,  79132,  86882,  91529,  91542,  94777,  96079,
        102407, 111759, 119145, 122886, 132660, 134130, 134853],
       dtype=int64),
 25: array([   231,    260,    527,   1198,   2028,   2571,   3578,   4993,
          5952,   7153,  58559,  59315,  60069,  68157,  68954,  74458,
         79132,  91529, 116797, 122912, 122916, 176371, 177593, 180095,
        187541, 187593], dtype=int64),
 26: array([ 47, 165, 296, 454, 457, 592, 593], dtype=int64),
 27: array([   2,   34,   48,   62,  260,  316,  356,  364,  367,  480,  590,
         595,  648,  745,  783,  808,  902,  911,  913,  920,  969,  986,
        1015, 1021, 1022, 1035, 1083, 1097, 1101, 1127, 1148, 1196, 1197,
        1198, 1201, 1207, 1210, 1250, 1262, 1270, 1276, 1287, 1584, 1721,
        1876, 1907, 1947, 2012, 2046, 2054, 2080, 2094, 2100, 2115, 2150,
        2151, 2161, 2406, 2407, 2478, 2529, 2565, 2628, 2640, 2687, 2944,
        2951, 3037, 3062, 3104, 3114, 3350, 3448, 3451, 3471, 3479, 3489,
        3508, 3555, 3654, 3681, 3836], dtype=int64),
 28: array([    6,    32,    50,    62,   110,   260,   293,   296,   316,
          318,   337,   345,   356,   475,   507,   508,   524,   529,
          541,   589,   590,   678,   714,   778,   858,  1047,  1080,
         1136,  1196,  1200,  1201,  1210,  1213,  1214,  1215,  1221,
         1222,  1233,  1240,  1245,  1249,  1253,  1256,  1266,  1276,
         1356,  1358,  1371,  1527,  1584,  1610,  1653,  1732,  1748,
         1785,  1921,  1953,  2021,  2023,  2028,  2105,  2193,  2194,
         2278,  2358,  2427,  2490,  2571,  2580,  2628,  2858,  2944,

In [12]:
favorable_movies = ratings_200[ ["movieId", "favorable"] ].groupby("movieId").sum()

favorable_movies = favorable_movies.sort_values(by="favorable", ascending=False)

favorable_movies.head()

         favorable
movieId
318             95
356             88
296             79
593             77
260             71